### ISSUE TITLE
Project references image on your machine

### ISSUE THREAD

**Issue by CliffAgius** [hjam40/Camera.MAUI#1]
Hi,

Great project and I hope it helps the MAUI Community Toolkit along but you might want to fix a build error I am seeing where the csproj is referencing an image on your machine.

[Here in the .csproj file](https://github.com/hjam40/Camera.MAUI/blob/a8e29eb22962b8a06995dd2022409d58be224b96/Camera.MAUI/Camera.MAUI.csproj#L53
)

**Comment by hjam40** [comment]
Thank you! I fixed it
