### ISSUE TITLE
access to usb-cam

### ISSUE THREAD

**Issue by reschresch** [hjam40/Camera.MAUI#115]
Hello,
I have an external usb-cam connected to my Android-Phone.
When I have a look at the avaiable devices with "cameraView.Cameras" I get only the internal camaras (back + front).

How can I connect it to the USB-Cam?

Best regards,

resch

**Comment by vrho94** [comment]
Hi i also need this to access my external USB camera. Did you get any solutions?

**Comment by reschresch** [comment]
Hello, currently I got no answer - and no solution. 
I can't believe no one else has this problem to connecting an external cam.

**Comment by vrho94** [comment]
Do you have any idea for other platforms and frameworks like for Java,Python...

**Comment by hjam40** [comment]
Hi,
In this library I'm using CameraManager GetCameraIdList for get all device cameras. If you could get usb cameras, maybe it is an application usb access permission error or an android internal error. Sorry, but I can not do nothing to fix it.

**Comment by vovanb** [comment]
any idea how to connect to USB camera?
