### ISSUE TITLE
Not recording video on IOS 17

### ISSUE THREAD

**Issue by shahidjameelbhatti** [hjam40/Camera.MAUI#122]
Hello, i am using this plugin to record video in my app, it was working perfectly before IOS 17, but now in IOS 17 its not recording the video, and saves an 0 bytes file, not a signle byte is written in that,
Can anyone help me fixing it for IOS 17?
Its very URGENT for me.
Thanks.

**Comment by Luca-21** [comment]
I have the same problem with android, did u find a solution?

**Comment by rdurish** [comment]
Same issue here, seems to work for android though.....

**Comment by harima34** [comment]
Same for me, did you solve it ?

**Comment by rdurish** [comment]
Completely stuck, iOS 17 with net8.0 saves as 0 byes with a successful result return.  @hjam40 I noticed a few changes yesterday?  Will you be pushing those up to nuget?

**Comment by blago83** [comment]
In MauiCameraView.cs -> StartRecordingAsync method remove the lines to create file if it doesn't exists. Delete the file if already exists. Now it's recoding video.

![image](https://github.com/hjam40/Camera.MAUI/assets/8492314/f7f452b6-0d8c-47c8-a986-c65dd8e95c1b)

**Comment by janusw** [comment]
FYI, this issue is fixed on [my fork](https://github.com/janusw/Camera.Maui) in [release 1.4.6](https://www.nuget.org/packages/CameraMaui/1.4.6).
