### ISSUE TITLE
No cameras detected

### ISSUE THREAD

**Issue by gbinnetov** [hjam40/Camera.MAUI#125]
private void cameraView_CamerasLoaded(object sender, EventArgs e)
{
    
    if (cameraView.Cameras.Count > 0)
    {
        cameraView.BarCodeDetectionEnabled = true;

        cameraView.Camera = cameraView.Cameras.First();
        MainThread.BeginInvokeOnMainThread(async () =>
        {
            await cameraView.StopCameraAsync();
            await cameraView.StartCameraAsync();
        });
    }
}

======================

cameraView.Cameras.Count = 0

**Comment by hjam40** [comment]
Hi,
It works fine. Maybe it is an access camera permission error on your application.
