### ISSUE TITLE
Setting zoom factor on Android does not make a difference

### ISSUE THREAD

**Issue by SimonBrettschneider** [hjam40/Camera.MAUI#13]
Hi

We have tried various camera settings, including the zoom factor, which seems to have no effect on the view port on Android (works fine on iOS).

 `cameraView.ZoomFactor = 2.5f;`

We have tested using a Google Pixel 7 Pro using version 1.3.1. Any thoughts?

**Comment by PeterVanVogelpoel** [comment]
Same problem here. Setting the Zoom dynamically works. But it does not stick.

**Comment by hjam40** [comment]
Hi Peter,

Now I published the version 1.3.4 and It fix the problem. Android Handler reads the ZoomFactor when start the preview/recording.

**Comment by PeterVanVogelpoel** [comment]
Hi Hector,
This all seems to work now. Great job! Again.
