### ISSUE TITLE
A Barcode (Zxing engine) Scanner Example?

### ISSUE THREAD

**Issue by dgerding** [hjam40/Camera.MAUI#140]
@hjam40 Thanks for a really evolved camera library! Big improvements versus earlier libraries.

I'm wondering if you are willing to post a short Bar Code scanner example project. The reason I ask is I can't seem to get any actual bar code recognition events to fire when I use the example projects. I have read through the example code (test project) and tried the bar code fragments from readme, but still getting no luck.

I've tried on Windows and Android devices. Everything runs but the BarCodeResults property never gets set and I can't seem to figure out what I'm doing wrong. Also, I've tried both on .net 6 and on .net 8 ( using simple upgrade project steps on each project). Both .net 6 and .net 8 builds run, but never detect any kind of bar codes or qr codes.

**If ANYONE can post a short git example of barcode scanning working (Zxing engine) that can scan EAN and UPC range of code style (I tied "All-1d" as setting) it would be a big help.**  I don't need to show bar code controls - just successfully recognize them.

Thanks
Dave Gerding

**Comment by hjam40** [comment]
Hi David,

thanks for your comment. The new nuget packages are not available in nuget yet. I’m working in compile then and I’m modifying the readme file to adapt it to the new packages. I hope in a few days it will be available (this week I have had a surprise work trip :( )

**Comment by hjam40** [comment]
Now available an excample with the new package in the readme file
