### ISSUE TITLE
Android video is saved upside down

### ISSUE THREAD

**Issue by prashant-bhandari** [hjam40/Camera.MAUI#141]
Hi, the video when recorded on android device is saved upside down.

Is there a work around for this issue?

**Comment by janusw** [comment]
I believe this is fixed in release [1.4.6](https://www.nuget.org/packages/CameraMaui/1.4.6) (and upwards), built from [my fork](https://github.com/janusw/Camera.Maui).

**Comment by prashant-bhandari** [comment]
It looks like there is only until 1.4.4 in nuget. Do I have to download another nuget? I have fixed it by adding the code directly and it is similar to yours with 270 degree rotation for front camera.

**Comment by janusw** [comment]
> It looks like there is only until 1.4.4 in nuget. Do I have to download another nuget?

I posted the link to the nuget above: https://www.nuget.org/packages/CameraMaui/1.4.6

The name is "CameraMaui".

**Comment by prashant-bhandari** [comment]
ah thanks for that. I did not pay attention on the name that minutely and thought it was the same
