### ISSUE TITLE
Any other alternative libraries?

### ISSUE THREAD

**Issue by romerotg** [hjam40/Camera.MAUI#148]
I stumbled upon this library because using the built-in media picker isn't reliable, as sometimes the background app gets closed while the camera app is open. That is particularly true for Samsung devices. But this library isn't really working well for me. I get random crashes when switching the camera (also present on the demo) and can't get the view to the correct size. It always resizes it incorrectly when I try full screen, making the image preview stretched and blurry. Somehow it makes the preview wider than it should.

Is there another library that I can try as an alternative?

**Comment by janusw** [comment]
I currently maintain my own fork, which fixes a few additional bugs. I don't know if it works any better for you, but you can try.

https://github.com/janusw/Camera.Maui
https://www.nuget.org/packages/CameraMaui

**Comment by janusw** [comment]
> But this library isn't really working well for me. I get random crashes when switching the camera (also present on the demo)

You should open an issue for that and provide the backtrace, a way to reproduce (if possible), and the device/OS on which you see this ...

**Comment by thomasgalliker** [comment]
My 5 cents:
https://www.nuget.org/packages/CameraScanner.Maui
https://github.com/thomasgalliker/CameraScanner.Maui

**Comment by romerotg** [comment]
I ended implementing my own camera view
