### ISSUE TITLE
Saved .Jpg files are limited resolution

### ISSUE THREAD

**Issue by pierre01** [hjam40/Camera.MAUI#18]
The saved files using the stream returned from  CameraView.TakePhotoAsync();
Are limited to 788x1054 on all the cameras listed on my Samsung S22 Ultra. (front and back)

Can we get an image with the full resolution of the selected camera?

Using version 1.3.5

**Comment by hjam40** [comment]
Hi Pierre,

Right now, Android photo resolution is limited to CameraView control size and device screen resolution, but I'm working on changing it. You could create a full screen control and the capture resolution should be higher.

**Comment by hjam40** [comment]
Hi Pierre,

In the new version you could set a Resolution in StartCameraAsync. This resolution will be used by TakePhotoAsync.

**Comment by FrKaram** [comment]
Gonna try that immediately, thanks

**Comment by pierre01** [comment]
Thank you for fixing this so fast. Thank you for your magnificent work ... It makes the camera finally usable without a picker.

**Comment by hjam40** [comment]
Hi Pierre, thank you for your support!
