### ISSUE TITLE
cameraView.TakePhotoAsync() return null on Android, while working normal on Windows

### ISSUE THREAD

**Issue by Aleph-Zero0** [hjam40/Camera.MAUI#22]
When I try to set `cv:CameraView`'s `IsVisible="False"`, or `WidthRequest` and `HeightRequest` to `0` `cameraView.TakePhotoAsync();` returnrs `null` when trying to run the program on Android, while on Windows it works perfectly fine. Also `WidthRequest` and `HeightRequest` of  `cv:CameraView` affects the quality of the `result` from `cameraView.TakePhotoAsync()` on Android, when again, on Windows it works perfectly fine.

Here are the snippets of code from `MainPage.xaml.cs` and `MainPage.xaml`

```C#
var stream = await cameraView.TakePhotoAsync();
  if (stream != null)
    {
        var result = ImageSource.FromStream(() => stream);
        displayImage.Source = result;
    }
```

```XAML
<cv:CameraView
    x:Name = "cameraView"
    IsVisible="True"
    WidthRequest="100"
    HeightRequest="20"
/>

<Image
    x:Name="displayImage"
    Source="dotnet_bot.png"
    IsVisible="True"
    Aspect="AspectFit"
/>
```

My devices`

- Windows 11 PC
- Android 11 on Sasmsung Galaxy S10
- Emulated Android 9 on Pixel 5

**Comment by hjam40** [comment]
Hi,

New version has been released. TakePhotoAsync is totally different in Android right now and it does not depends from the preview visibility.
