### ISSUE TITLE
Slow QR code processing on Android due to multiple QR decoding tasks running simultaneously

### ISSUE THREAD

**Issue by arekzimny** [hjam40/Camera.MAUI#27]
I've noticed that the decoding of QR codes appears to run on ThreadPool tasks based on a timer without any consideration for existing tasks. I can sometimes see upwards of 10 threads running simultaneously depending on how I set the frame rate. This leads to a couple of issues for me:

1. The app slows to a crawl and the camera begins to stutter as more tasks are started. This is especially noticeable on older smartphones.
2. Once a barcode is detected the user is directed to a page that asks for more information. However, they can hit the back button and go back to the QR scanning page. Sometimes, one of the still-running threads will finish and cause the BarcodeDetected event to fire even though there is no QR code in front of the camera.

**Comment by luis95gr** [comment]
Hi, I have the same issue even with recent smartphones (S23 and Pixel 7), I can't use this plugin due to the lagging.

**Comment by scriptBoris** [comment]
I can confirm the problem, it takes a very long time to recognize QR codes and poor performance

**Comment by scriptBoris** [comment]
> Hi, The new version is available. Right now, you could control better the barcode detection mode with this properties: BarCodeDetectionFrameRate BarCodeDetectionMaxThreads BarCodeOptions ControlBarcodeResultDuplicate
> 
> The performance should be better depending the parameter configuration (specially BarCodeDetectionMaxThreads)

[2023-05-12 20-18-14.zip](https://github.com/hjam40/Camera.MAUI/files/11465018/2023-05-12.20-18-14.zip)
I record screen video that 1D barcodes not recognized (ZIP). But QR codes is read by 1-3 seconds.

How fix problem with 1D barcodes?

**Comment by scriptBoris** [comment]
On real android device, Camera.MAUI no read QR codes too 😒

**Comment by hjam40** [comment]
Hi Boris,

I have tested it in 3 Android devices and it works fine for QR detection.... Make sure to initialize correctly the parameters:
CameraView.BarcodeDecodeOptions.PossibleFormats = new List<BarcodeFormat> { BarcodeFormat.QR_CODE };
...

By the way, it is not this plugging that detects the codes, this pluggin uses ZXing for that. The plugging only pass a camera capture to the ZXing decoder.

**Comment by scriptBoris** [comment]
> Привет, Борис,
> 
> Я протестировал его на 3 устройствах Android, и он отлично работает для обнаружения QR.... Убедитесь, что правильно инициализированы параметры: CameraView.BarcodeDecodeOptions.PossibleFormats = new List { BarcodeFormat.QR_CODE }; ...
> 
> Кстати, не этот плагин обнаруживает коды, этот плагин использует для этого ZXing. Подключение передает только захват камеры на декодер ZXing.

![image](https://github.com/hjam40/Camera.MAUI/assets/29772096/9f6e3fd8-ebfd-4bcc-941b-0bae28b975e1)
No throw break point...

**Comment by hjam40** [comment]
Hi,

Sorry, but I don't understand your message. With this configuration I have read your code from an Android device in less of 1 second:

```c#
        cameraView.BarCodeOptions = new ZXingHelper.BarcodeDecodeOptions
        {
            AutoRotate = true,
            PossibleFormats = { BarcodeFormat.EAN_13 },
            ReadMultipleCodes = false,
            TryHarder = false,
            TryInverted = true
        };
```
