### ISSUE TITLE
getMicrophones error on older Androids

### ISSUE THREAD

**Issue by NZLoki** [hjam40/Camera.MAUI#30]
example on Android 5
Java.Lang.NoSuchMethodError
  Message=no non-static method "Landroid/media/AudioManager;.getMicrophones()Ljava/util/List;"

0x12 in Android.Media.AudioManager.get_Microphones at /Users/runner/work/1/s/xamarin-android/src/Mono.Android/obj/Release/net7.0/android-33/mcw/Android.Media.AudioManager.cs:1537,6
0x177 in Camera.MAUI.Platforms.Android.MauiCameraView.InitDevices  C#

Looks like it just needs an API check _similar_ to the following

`if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.P) {
    List<MicrophoneInfo> mics = am.getMicrophones();
    ...
} else {
    AudioDeviceInfo[] deviceInfo = am.getDevices(AudioManager.GET_DEVICES_INPUTS);
    ...
}`

in Android/MauiCameraView.cs : InitDevices() : line 92

several examples online search for:
_no non-static method "Landroid/media/AudioManager;.getMicrophones()Ljava/util/List;"_

**Comment by hjam40** [comment]
Hi,

Thank you for the advice. I will add a version check, but Android does not use Microphone list for recording (you can't set a specific microphone...)
