### ISSUE TITLE
android 8 noSuchMethodError

### ISSUE THREAD

**Issue by gokhangencer** [hjam40/Camera.MAUI#35]
I have also comment out  the following lines but getMicrophones() method is not found error thrown. 
tested on emulator and test phone.

//if (cameraView.NumMicrophonesDetected > 0)
            //    cameraView.Microphone = cameraView.Microphones.First();

exception:
![image](https://github.com/hjam40/Camera.MAUI/assets/5635828/bd683c79-214a-4c9b-b042-a273d2873b30)

call stack:
![image](https://github.com/hjam40/Camera.MAUI/assets/5635828/ced4b0d0-6247-48ef-9e66-45ec643ca016)

thank you.

**Comment by hjam40** [comment]
Hi,

In the last version of the plugging, microphones read in Android is limited to API>=30:
```c#
            if (OperatingSystem.IsAndroidVersionAtLeast(30))
            {
                cameraView.Microphones.Clear();
                foreach (var device in audioManager.Microphones)
                {
                    cameraView.Microphones.Add(new MicrophoneInfo { Name = "Microphone " + device.Type.ToString() + " " + device.Address, DeviceId = device.Id.ToString() });
                }
            }
``` 

But as I said in the other post, Android does not use microphones list for video recording. You don't need initialize it. It use the default microphone input in the device.

**Comment by hjam40** [comment]
Hi

The previous package versions were not compatible with Android 8. The new version 1.4.1 is compatible.
