### ISSUE TITLE
No license file

### ISSUE THREAD

**Issue by cabbruzzese** [hjam40/Camera.MAUI#82]
Nuget package says license is [MIT](https://licenses.nuget.org/MIT), but there is none in the repository. Does a License file need added?

Reference for license in project file
https://github.com/hjam40/Camera.MAUI/blob/d9ee42a428b9ee41efff624fe01643b62c7781e6/Camera.MAUI/Camera.MAUI.csproj#L30

**Comment by jeremy-bridges** [comment]
We'd like to see this too. @hjam40, could this be further clarified in the repository? In a license.md would be ideal, like this one from the payload project:

https://github.com/payloadcms/payload/blob/main/license.md

Thanks for considering it!

**Comment by hjam40** [comment]
Added license file.
