### ISSUE TITLE
Access raw camera feed

### ISSUE THREAD

**Issue by KonstantinHamm** [hjam40/Camera.MAUI#9]
As Gerald Versluis in his Video stated: it would be interesting if we could get access to the raw  camera feed with this library. Then it would be possible to create augmented reality apps with .NET MAUI.

**Comment by hjam40** [comment]
Hi Constantine,
 If you set AutoSnapShotSeconds (float), You get the AutoSnapShotStream refreshed every x.y seconds (it is as get raw access to the frames), but you must keep in mind the performance. Windows and iOS platforms stop the camera if processing time between frames is so long.
